apiVersion: batch/v1
kind: Job
metadata:
  name: argotest
spec:
  template:
    spec:
      containers:
      - name: argo
        image: daewood/argo
        args: ["list","--token","eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tcGc3MnciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImQ1ZmMzZmQxLWZhYjktMTFlNy1hMzc0LWZhMTYzZWNmMjk5YyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.lea6FYpkGIQ0FT4-z3oU3tUI8e0wx3vD7Dn8rI3uG6qdWFIj22oIqIlZQ_k8iD52ZOzfq-mYEzdq3OwIlCFz_2kNj7iGHaaJcdO_UPsQL2YbIvCXgDvGzY7AwyG3EidoZcnPlMwffjjJnH2XHLwc1y_3KsMa4WEvmemBtwpm-b6EzEzdGsY9TrC7vp5D4ay5zGK9FP-vIbY0x71uD2TrQPba_DSgHC9o9dpd3Jb9bmK-gwSW2t2KI5nqxgflEY5F99u84qVdlN2sqKMalu_xBcax4gb04FYn8AHNg2c8xLltoIzNPgVQkvWKs2E_S8bkGJ4uzLpYczQc0vgNL46rzg","--insecure-skip-tls-verify","--server", ]
      restartPolicy: Never
  backoffLimit: 4
